// Code generated by protoc-gen-go.
// source: events.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	events.proto

It has these top-level messages:
	Aggregate
	UserCreated
	UserNameSet
	UserEmailSet
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Aggregate struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	At      int64  `protobuf:"varint,3,opt,name=at" json:"at,omitempty"`
}

func (m *Aggregate) Reset()                    { *m = Aggregate{} }
func (m *Aggregate) String() string            { return proto.CompactTextString(m) }
func (*Aggregate) ProtoMessage()               {}
func (*Aggregate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Aggregate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Aggregate) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Aggregate) GetAt() int64 {
	if m != nil {
		return m.At
	}
	return 0
}

// UserCreated defines a user creation event
type UserCreated struct {
	Aggregate *Aggregate `protobuf:"bytes,1,opt,name=aggregate" json:"aggregate,omitempty"`
}

func (m *UserCreated) Reset()                    { *m = UserCreated{} }
func (m *UserCreated) String() string            { return proto.CompactTextString(m) }
func (*UserCreated) ProtoMessage()               {}
func (*UserCreated) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserCreated) GetAggregate() *Aggregate {
	if m != nil {
		return m.Aggregate
	}
	return nil
}

type UserNameSet struct {
	Aggregate *Aggregate `protobuf:"bytes,1,opt,name=aggregate" json:"aggregate,omitempty"`
	Name      string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *UserNameSet) Reset()                    { *m = UserNameSet{} }
func (m *UserNameSet) String() string            { return proto.CompactTextString(m) }
func (*UserNameSet) ProtoMessage()               {}
func (*UserNameSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserNameSet) GetAggregate() *Aggregate {
	if m != nil {
		return m.Aggregate
	}
	return nil
}

func (m *UserNameSet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserEmailSet struct {
	Aggregate *Aggregate `protobuf:"bytes,1,opt,name=aggregate" json:"aggregate,omitempty"`
	Email     string     `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
}

func (m *UserEmailSet) Reset()                    { *m = UserEmailSet{} }
func (m *UserEmailSet) String() string            { return proto.CompactTextString(m) }
func (*UserEmailSet) ProtoMessage()               {}
func (*UserEmailSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserEmailSet) GetAggregate() *Aggregate {
	if m != nil {
		return m.Aggregate
	}
	return nil
}

func (m *UserEmailSet) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*Aggregate)(nil), "main.Aggregate")
	proto.RegisterType((*UserCreated)(nil), "main.UserCreated")
	proto.RegisterType((*UserNameSet)(nil), "main.UserNameSet")
	proto.RegisterType((*UserEmailSet)(nil), "main.UserEmailSet")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x85, 0x49, 0xda, 0x2a, 0xb9, 0x2d, 0x0a, 0xc1, 0x21, 0x63, 0xc9, 0xd4, 0xc5, 0x0e, 0xba,
	0xba, 0x88, 0x74, 0x15, 0x49, 0xf1, 0x07, 0x5c, 0xe9, 0xa5, 0x04, 0x4c, 0x2a, 0x69, 0xe8, 0xef,
	0x97, 0xa4, 0xaf, 0xef, 0xcd, 0xef, 0x6d, 0x39, 0x70, 0xbe, 0xef, 0x84, 0x0b, 0x0d, 0x6d, 0xe4,
	0xe3, 0xda, 0xff, 0x85, 0x25, 0x2e, 0xb2, 0x74, 0x68, 0xbd, 0x1e, 0x40, 0xbc, 0xcf, 0x73, 0xa0,
	0x19, 0x23, 0xc9, 0x07, 0xe0, 0x76, 0x52, 0xac, 0x65, 0x9d, 0x30, 0xdc, 0x4e, 0x52, 0xc1, 0xfd,
	0x46, 0x61, 0xb5, 0x8b, 0x57, 0xbc, 0x65, 0x5d, 0x65, 0x8e, 0x98, 0x9a, 0x18, 0x55, 0xd1, 0xb2,
	0xae, 0x30, 0x1c, 0xa3, 0x7e, 0x83, 0xfa, 0x7b, 0xa5, 0xf0, 0x11, 0x08, 0x23, 0x4d, 0xf2, 0x19,
	0x04, 0x1e, 0xd6, 0xec, 0xab, 0x5f, 0x1e, 0xfb, 0xb4, 0xd7, 0x9f, 0xc7, 0xcc, 0xa5, 0xa1, 0xbf,
	0x76, 0xfa, 0x13, 0x1d, 0x8d, 0x14, 0xaf, 0xa4, 0xa5, 0x84, 0xd2, 0xa3, 0xa3, 0xfc, 0x45, 0x61,
	0xf2, 0x5b, 0x8f, 0xd0, 0x24, 0xe3, 0xe0, 0xd0, 0xfe, 0xde, 0xa0, 0x7c, 0x82, 0x8a, 0x12, 0x7a,
	0x72, 0xee, 0xe1, 0xe7, 0x2e, 0x1f, 0xee, 0xf5, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x39, 0x0c, 0x82,
	0x82, 0x48, 0x01, 0x00, 0x00,
}
